name = "BooleanInference"
uuid = "d12a6243-8379-43cb-9459-098119da1519"
version = "1.0.0-DEV"
authors = ["nzy1997"]

[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GenericTensorNetworks = "3521c873-ad32-4bb4-b63d-f4f178f42b49"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
OptimalBranchingCore = "c76e7b22-e1d2-40e8-b0f1-f659837787b8"
ProblemReductions = "899c297d-f7d2-4ebf-8815-a35996def416"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TropicalNumbers = "b3a74e9c-7526-4576-a4eb-79c0d4c32334"

[compat]
BitBasis = "0.9.10"
CairoMakie = "0.15.6"
Colors = "0.13.1"
Compose = "0.9.6"
DataStructures = "0.18.22"
GenericTensorNetworks = "4"
GraphMakie = "0.6.3"
GraphPlot = "0.6.2"
Graphs = "1.13.1"
NetworkLayout = "0.4.10"
OptimalBranchingCore = "0.1"
ProblemReductions = "0.3.5"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
TropicalNumbers = "0.6.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
